### Today we are going to perform the simple classification of the amazon reviews' sentiment.

### Please, download the dataset amazon_baby.csv.

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.linear_model import LogisticRegression

def remove_punctuation(text):
    import string
    #translator = str.maketrans('', '', string.punctuation)
    # aha,this is also because z cannot be the only argument
    #If extra values exist as the first and second arguments, they are added to this mapping as additional 
    #characters to be translated (this is why the author selected '' and ''; he doesn't want extra characters
    #to be translated):
    return text.translate(str.maketrans(string.punctuation, ' ' * len(string.punctuation))).replace(' '*4, ' ').replace(' '*3, ' ').replace(' '*2, ' ').strip()


baby_df = pd.read_csv('/home/user/Pulpit/pani_ela_data_science/temat4/amazon_baby.csv')
baby_df.head()

name  \
0                           Planetwise Flannel Wipes   
1                              Planetwise Wipe Pouch   
2                Annas Dream Full Quilt with 2 Shams   
3  Stop Pacifier Sucking without tears with Thumb...   
4  Stop Pacifier Sucking without tears with Thumb...   

                                              review  rating  
0  These flannel wipes are OK, but in my opinion ...       3  
1  it came early and was not disappointed. i love...       5  
2  Very soft and comfortable and warmer than it l...       5  
3  This is a product well worth the purchase.  I ...       5  
4  All of my kids have cried non-stop when I trie...       5

## Exercise 1 (data preparation)
a) Remove punctuation from reviews using the given function.   
b) Replace all missing (nan) revies with empty "" string.  
c) Drop all the entries with rating = 3, as they have neutral sentiment.   
d) Set all positive ($\geq$4) ratings to 1 and negative($\leq$2) to -1.

In [17]:
# Bacause of the above reason, I'll do b) first ( than a) )
# b)
baby_df['review'] = baby_df['review'].fillna('')
baby_df["review"][30]

'Beautiful little book A great little short story saying I Love You Keeps the attention of the baby and then the baby can actually turn the pages and hold on to it when you are finished interacting with it'

In [18]:
#a)
baby_df['review'] = baby_df['review'].apply(remove_punctuation)
#short test: 
baby_df["review"][4] == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'

False

In [19]:
baby_df["review"][4]

'All of my kids have cried non stop when I tried to ween them off their pacifier until I found Thumbuddy To Love s Binky Fairy Puppet It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from it This is a must buy book and a great gift for expecting parents You will save them soo many headaches Thanks for this book You all rock'

In [30]:
#b)

#short test:
baby_df["review"][38] == baby_df["review"][38]

True

In [31]:
baby_df.drop(baby_df[baby_df.rating == 3].index, inplace=True)

In [33]:
#c)
#df = df.drop(df[df.score < 50].index)
#In place version (as pointed out in comments)
#df.drop(df[df.score < 50].index, inplace=True)

#baby_df.drop(baby_df[baby_df.review == 3].index, inplace=True)
baby_df[baby_df.rating < 3]

#short test:
sum(baby_df["rating"] == 3)

0

In [58]:
#d) it seems not to listen to that
baby_df = pd.read_csv('/home/user/Pulpit/pani_ela_data_science/temat4/amazon_baby.csv')
baby_df.drop(baby_df[baby_df.rating == 3].index, inplace=True)

baby_df.loc[(baby_df.rating < 3),'rating']= -1
#baby_df.loc[(baby_df.rating > 3),'rating']= 1
#baby_df.loc[(baby_df.rating > 3),'rating']= 1
baby_df[baby_df.rating == 3]

#short test:
sum(baby_df["rating"]**2 != 1)
#print(baby_df[baby_df.rating == 1])
baby_df

name  \
1                                   Planetwise Wipe Pouch   
2                     Annas Dream Full Quilt with 2 Shams   
3       Stop Pacifier Sucking without tears with Thumb...   
4       Stop Pacifier Sucking without tears with Thumb...   
5       Stop Pacifier Sucking without tears with Thumb...   
...                                                   ...   
183526  Baby Teething Necklace for Mom Pretty Donut Sh...   
183527  Baby Teething Necklace for Mom Pretty Donut Sh...   
183528   Abstract 2 PK Baby / Toddler Training Cup (Pink)   
183529  Baby Food Freezer Tray - Bacteria Resistant, B...   
183530  Best 2 Pack Baby Car Shade for Kids - Window S...   

                                                   review  rating  
1       it came early and was not disappointed. i love...       5  
2       Very soft and comfortable and warmer than it l...       5  
3       This is a product well worth the purchase.  I ...       5  
4       All of my kids have cried non-stop when I trie...       5  
5       When the Binky Fairy came to our house, we did...       5  
...                                                   ...     ...  
183526  Such a great idea! very handy to have and look...       5  
183527  This product rocks!  It is a great blend of fu...       5  
183528  This item looks great and cool for my kids.......       5  
183529  I am extremely happy with this product. I have...       5  
183530  I love this product very mush . I have bought ...       5  

[166752 rows x 3 columns]

## CountVectorizer
In order to analyze strings, we need to assign them numerical values. We will use one of the simplest string representation, which transforms strings into the $n$ dimensional vectors. The number of dimensions will be the size of our dictionary, and then the values of the vector will represent the number of appereances of the given word in the sentence.

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
reviews_train_example = ["We like apples",
                   "We hate oranges",
                   "I adore bananas",
                   "We like like apples and oranges",
                   "They dislike bananas"]
y_train_example = [1,1,0,1,0]

X_train_example = vectorizer.fit_transform(reviews_train_example)

print(vectorizer.get_feature_names())
print(X_train_example.todense())
model_trial = LogisticRegression()
model_trial.fit(X_train_example, y_train_example)
# CountVectorizer przedstawia zadane zdania za pomoca ilosci pojawien w zdaniu danego wyrazu ze zlownika
# w postaci listy
len(model_trial.coef_[0])

['adore', 'and', 'apples', 'bananas', 'dislike', 'hate', 'like', 'oranges', 'they', 'we']
[[0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 2 1 0 1]
 [0 0 0 1 1 0 0 0 1 0]]


/home/user/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


10

In [33]:
model_trial.predict(np.array([0,1,1,0,0,0,2,1,0,1]).reshape(1,-1))

array([1])

In [ ]:
reviews_test_example = ["They like bananas",
                   "We hate oranges bananas and apples",
                   "We love bananas"] #New word!

X_test_example = vectorizer.transform(reviews_test_example)

print(X_test_example.todense())

We should acknowledge few facts. Firstly, CountVectorizer does not take order into account. Secondly, it ignores one-letter words (this can be changed during initialization). Finally, for test values, CountVectorizer ignores words which are not in it's dictionary.

In [5]:
# count vectorizer does not take order into account. It also does not take single letters into account.
# For test values it ignores words which are not in its dictonary.

## Exercise 2 
a) Split dataset into training and test sets.     
b) Transform reviews into vectors using CountVectorizer. 

In [ ]:
#a)


In [ ]:
#b)


## Exercise 3 
a) Train LogisticRegression model on training data (reviews processed with CountVectorizer, ratings as they were).   
b) Print 10 most positive and 10 most negative words.

In [10]:
#a)
# And it should learn which word is seen in positive reviews and which in negative
# And based on that we should be able to know whch word is thought to appear in positive/negative reviews
# I jako, ze to jest LogisticRegression to powinno nam jeszcze powiedziec z jakim prawdopodobienstwem

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
# Czyli roumiem, ze trening, ktɔry sie tutaj odbywa polega na ocenieniu czydane s᷆owo jest pozytywne czyli
model.fit(X_train_vect, y_train)

# Tak jest:
#predict(self, X)	Predict class labels for samples in X.
#predict_log_proba(self, X)	Log of probability estimates.
#predict_proba(self, X)	Probability estimates.

# czyli moze tak przez analogi efo linear classifiers:
# uczy sie prawdopodobienstw z jakimi kazdy z wyrazow nalezy do danej kategorii, czyli parwdopodobiestaw sa
# dobra juz widze

NameError: name 'X_train_vect' is not defined

In [11]:
#b)
Coefficient of the features in the decision function.
Dobra - poki co nie mam odpwiedzi ani nie mam, wiec pozostaje 

#coef_ is of shape (1, n_features) when the given problem is binary. In particular, when multi_class=
#'multinomial', coef_ corresponds to outcome 1 (True) and -coef_ corresponds to outcome 0 (False).
#hint: model.coef_, vectorizer.get_feature_names()

# but watch out czy te coeffcy to prawdopodobienstwa - nie zja

# Aha, to bylo tak, ze w tym recznym modelu, do mnozenia - bralo sie log prawdopodobienstw, bo wtdy nie
# wychodzily absurdalnie male liczby

# model.coef_.shape - wspolczynnik dla kazdego slowa (wspolczynnik, czyli zgauje ze cos na ksztalt prawdop.)


SyntaxError: invalid syntax (<ipython-input-11-324658a2069d>, line 2)

In [ ]:
# Decision function zwraca odleglosc do hyperplanu nie podzialu decyzji, nie wiem jak to sie ma do DOKLADNIE
# do prawdopodobiestw 

In [ ]:
most_probable_positives = []
most_probable_negatives = []
model_coefs = list(model.coef_[0])
for i in range(10):
    index_max = np.argmax(model_coefs)
    index_min = np.argmin(model_coefs)
    max_value = model_coefs.pop(index_max)
    min_value = model_coefs.pop(index_min)
    most_probable_positives.append( vectorizer.get_feature_names()[index_max] )
    most_probable_negatives.append( vectorizer.get_feature_names()[index_min] )

In [20]:
print(len(model.decision_function(X_train_vect))) # 1 - These scores can be used to make class predictions as follows:
print(len(model.coef_[0])) # 2
print(np.shape(X_train_vect))
# I was wandering, which coefficients 1 or 2, should be used to estimate words' probabilites.
# Confidence scores per (sample, class) combination - decision function, so I guess that this function id used
# for predictoin of samples , and I guess that coef_s are for predictions of single words
# Coefficient of the features in the decision function. 
(X_train_vect[0].todense()[0])
# Tak przeprowadzilas symulacje i to faktycznie coefsy odpowiadajɛ cechom
# sigmoid( dot([val1, val2], lr.coef_) + lr.intercept_ ) 
print [1./(1+np.exp(-x)) for x in scores]

NameError: name 'X_train_vect' is not defined

In [ ]:
model.predict(X_test_vect)
ValueError: X has 141188 features per sample; expecting 52648
# Aha, czyli on robi predykcje dla poszczegɔlnych slow, no ale nie no - wspolczynniki kolejnych slow sluza za 
# skladowe, sa atrybutami, i tylko powinny sluzyc do przewidywania prob.

# you should build test based on train dictionary- this should solve the problem.

## Exercise 4 
a) Predict the sentiment of test data reviews.   
b) Predict the sentiment of test data reviews in terms of probability.   
c) Find five most positive and most negative reviews.   
d) Calculate the accuracy of predictions.

In [ ]:
#a)
# no i on sie uczy prawdopodobienstw slow i na ich podstawie powienien przewidzeic zdanie- i co , i nic!

In [ ]:
#b)

#hint: model.predict_proba()

In [ ]:
#c) 
#len(X_test.review) #55029
#hint: use the results of b)

# w liscie prawdopodobienstw bylo ponumerowane po kolei natomiast ze wzgledu na losowosc na liscie X_test
# jest nie po kolie co moze powodowac problemy ze znakami

# However, as chceked empirically, this numeration turned to be good for this example.
# The returned estimates for all classes are ordered by the label of classes, so in this case [P(1),P(-1)]

In [1]:
# na wszelki wypadek to zachowam jakby by᷆o zle , doprawdy nie wiem o co to chodzi z tymi pojedynczymi 
# niepasujacymi
#len( np.sort(list(test_probab[:,0])) )

most_positive_rev_ind = []
most_negative_rev_ind = []
positive_prob = list(test_probab[:,1])
negative_prob = list(test_probab[:,0])
for i in range(5):
    max_pos_ind = np.argmax(positive_prob) 
    max_neg_ind = np.argmax(negative_prob) 
    max_pos_value = positive_prob.pop(max_pos_ind)
    max_pos_value = negative_prob.pop(max_neg_ind)
    most_positive_rev_ind.append(max_pos_ind)
    most_negative_rev_ind.append(max_neg_ind)

# Indices of the most positive and the most negative reviews:
print(most_positive_rev_ind)
print(most_negative_rev_ind)
positive_prob[53755]
# No ok, to mnie troche dziwi, 4 z pieciu wynikow w kazdej z kolumn sa jaknajbardziej sensowne, ale skrajne w 
# obu sa absurdalne - o co chodzi?
# i wogogole to uzyskujac te prawdopodobienstwa przy uzyciu innej funkcji
# okej, to moze sie zgadzac, ze wzgledu na roznice w numeracji, bo znajdowanie wartosci wykonuje sie potem 
# przy uzyciu funkcji iloc, ktora jest inclusive czy cos, ale przy wybieraniu konkretnych elementɔw to nie 
# powinno miec znaczenia
# w sensie - positive probabs sa lista, no i ajnie 

NameError: name 'test_probab' is not defined

In [2]:
# Okey it makes sense, when we changed the order - it turned out that, order is different that you thought
#before thus if we get results close to zero in first column, it means high probability of being positive
# and results close to zero in second column - it means most negative results

In [ ]:
# Ok, most positive to tam, gdzie pierwsza kolumna dazy do zera, ok, czyli najwieksze to te najbardziej
# negatywne, a to wynika z kolejnosci sortownia wykonywanej przez argsort.

In [ ]:
# Mozesz do tego wrocic, i przanalizowac caly workflow regresji logistycznej i tych wynikɔw, i czemu taki 
# odwrocony order ma miejsce, ale nie teraz, tylko w okienku, bo teraz to masz 
# zmecznie materialu z tym zwiazane.

In [ ]:
#d) 


## Exercise 5
In this exercise we will limit the dictionary of CountVectorizer to the set of significant words, defined below.


a) Redo exercises 2-5 using limited dictionary.   
b) Check the impact of all the words from the dictionary.   
c) Compare accuracy of predictions and the time of evaluation.

In [ ]:
# a)
# 3) uzywajac tego typu kodu do do skroconeg osubsetu z niewyjascnionych przyczy nie eychodzi
# zniwu jakas zabawa z indexami, wiec juz sie tym nie baz, bo na tym etaoie to szkoda czasu
most_probable_positives_subset = []
most_probable_negatives_subset = []
model_coefs_subset = list(model_subset.coef_[0])
'''for i in range(9):
    index_max_subset = np.argmax(model_coefs_subset)
    index_min_subset = np.argmin(model_coefs_subset)
    max_value_subset = model_coefs_subset.pop(index_max_subset)
    min_value_subset = model_coefs_subset.pop(index_min_subset)
    most_probable_positives_subset.append( vectorizer_subset.get_feature_names()[index_max_subset] )
    most_probable_negatives_subset.append( vectorizer_subset.get_feature_names()[index_min_subset] )
    
print('Most probable positives:')
print(most_probable_positives_subset)
print('Most probavle negatives:')
print(most_probable_negatives_subset)'''
model_coefs_subset

# Znowoz nie wiem czemu w tym przypadku sie pojebala kolejnosc ze w pierwszje kolumnie sa jednak pozytyne
# a nie negatywne, a nie na odworɔt, ale coz
# Poki co dajmy temu spokɔj, mozejsz wrocic do tego w okinwku

In [ ]:
#b)


In [ ]:
#c)
# timeit dokonczysz na cwikach - bo to chyba nie trudne, ale zmudne
#hint: %time, %timeit